version: '3'
networks:
  config-server_myweb:
    external: true
services:
  database2:
    container_name: "database2"
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - config-server_myweb
    environment:
      MYSQL_USER: "nuguri"
      MYSQL_PASSWORD: "bom"
      MYSQL_DATABASE: "testdb"
  clientserver2:
    container_name: "clientserver2"
    image: spring-cloud-eureka-client:1.0
    ports:
      - "8001:8001"
    networks:
      - config-server_myweb
    environment:
      RUN_MESSAGE: "HELLO !!"
      DATABASESERVER_PORT: "3306"

