server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: refresh,env

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://database2:3306/testdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: nuguri
    password: bom
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true

security:
  oauth2:
    resource:
      user-info-uri: http://authserver:8901/auth/user

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.example: DEBUG