server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: refresh,env

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/